os:
- linux
- osx
language: node_js
node_js:
- '10'
- '12'
- '14'
services:
  - docker
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start &
- sleep 3
script:
- ./examples/basic-cli-test.sh
- ./examples/example.js
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    docker build -t local/html5-to-pdf-example -f examples/Dockerfile . && docker run --rm -i --cap-add=SYS_ADMIN local/html5-to-pdf-example;
  fi
after_success:
- yarn lint
deploy:
  provider: npm
  email: thepeterdemartini@gmail.com
  api_key:
    secure: "iFlKrNUI5MbONm3oMJr+YQIZ+am5mPFRBSMwDstmI8Yod+2uWsZkQ+D35g8osGHr/A2/889/tOHGl/QS4adENO0Ui6mWyqQq+H97zsB555Wy5nIUmE6i++AWrm+w+GH3lz6TCTVyGKWmXp/cFZ7Qxxsge0Z09EON1PsKgb6Fgbg="
  on:
    tags: true
    repo: peterdemartini/html5-to-pdf
